# Generated by Django 4.1.3 on 2024-03-23 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_signup_confirmpass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='confirmpass',
        ),
    ]
