# Generated by Django 4.1.3 on 2024-05-07 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
